language: python
sudo: false




python:
  - '3.6'


install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .



after_success:
- coveralls
